from typing import Optional
import datetime
import decimal

from sqlalchemy import BigInteger, Date, DateTime, Double, Index, Integer, SmallInteger, String, TIMESTAMP, Text, text
from sqlalchemy.dialects.mysql import MEDIUMBLOB, TINYINT
from sqlalchemy.orm import Mapped, mapped_column

from app.db.mysql_connection import MySQLBase


class Student(MySQLBase):
    __tablename__ = 'students'
    __table_args__ = (
        Index('SubGroupID', 'SubGroupID'),
        Index('course', 'CourseNumber'),
        Index('dopusk', 'dopusk'),
        Index('dormroomid', 'dormroomid'),
        Index('epvosend', 'epvosend'),
        Index('login', 'Login'),
        Index('login_password', 'Login', 'Password'),
        Index('minorid', 'minorid'),
        Index('nobdid', 'nobdid'),
        Index('nobdstudentid', 'nobdstudentid'),
        Index('pedquota', 'pedquota'),
        Index('percoid', 'percoid'),
        Index('percoidentifier', 'percoidentifier'),
        Index('prich', 'prich'),
        Index('specializationID', 'specializationID'),
        Index('students_curriculumID', 'TypCurriculumID'),
        Index('students_groupID', 'groupID'),
        Index('students_iinplt', 'iinplt'),
        Index('students_is_student', 'isStudent'),
        Index('students_professionID', 'ProfessionID'),
        Index('students_specializationID', 'specializationID'),
        Index('students_studyformID', 'StudyFormID'),
        Index('telegramid', 'telegramid'),
        Index('tsqupta', 'tsqupta')
    )

    StudentID: Mapped[int] = mapped_column(Integer, primary_key=True)
    firstname: Mapped[str] = mapped_column(String(128), nullable=False)
    lastname: Mapped[str] = mapped_column(String(128), nullable=False)
    mail: Mapped[str] = mapped_column(String(512), nullable=False)
    iinplt: Mapped[str] = mapped_column(String(32), nullable=False)
    studyCalendarID: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    dormroomid: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    SubGroupID: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'1'"))
    minorid: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'0'"))
    prich: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'0'"))
    dopusk: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'1'"))
    ikt: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"), comment='ИКТ | ОИТ2016')
    telegramid: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("'0'"))
    modified: Mapped[datetime.datetime] = mapped_column(TIMESTAMP, nullable=False, server_default=text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    pedquota: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'0'"))
    tsqupta: Mapped[int] = mapped_column(TINYINT, nullable=False, server_default=text("'0'"))
    nobdstudentid: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    nobdid: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    epvosend: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    patronymic: Mapped[Optional[str]] = mapped_column(String(128))
    BirthDate: Mapped[Optional[datetime.date]] = mapped_column(Date)
    StartDate: Mapped[Optional[datetime.date]] = mapped_column(Date)
    Login: Mapped[Optional[str]] = mapped_column(String(128))
    Password: Mapped[Optional[str]] = mapped_column(String(128))
    phone: Mapped[Optional[str]] = mapped_column(String(256))
    adress: Mapped[Optional[str]] = mapped_column(String(512))
    SexID: Mapped[Optional[int]] = mapped_column(Integer)
    NationID: Mapped[Optional[int]] = mapped_column(Integer)
    StudyFormID: Mapped[Optional[int]] = mapped_column(Integer)
    PaymentFormID: Mapped[Optional[int]] = mapped_column(Integer)
    StudyLanguageID: Mapped[Optional[int]] = mapped_column(Integer)
    photo: Mapped[Optional[bytes]] = mapped_column(MEDIUMBLOB)
    ProfessionID: Mapped[Optional[int]] = mapped_column(Integer)
    CourseNumber: Mapped[Optional[int]] = mapped_column(Integer)
    rnn: Mapped[Optional[str]] = mapped_column(String(32))
    sikplt: Mapped[Optional[str]] = mapped_column(String(32))
    RoleID: Mapped[Optional[int]] = mapped_column(Integer)
    TypCurriculumID: Mapped[Optional[int]] = mapped_column(Integer)
    enterexams: Mapped[Optional[str]] = mapped_column(Text)
    enterexamskz: Mapped[Optional[str]] = mapped_column(Text)
    enterexamsen: Mapped[Optional[str]] = mapped_column(Text)
    pasteduinforu: Mapped[Optional[str]] = mapped_column(String(512))
    pasteduinfokz: Mapped[Optional[str]] = mapped_column(Text)
    pasteduinfoen: Mapped[Optional[str]] = mapped_column(Text)
    transcriptnumber: Mapped[Optional[str]] = mapped_column(String(128))
    transcriptseries: Mapped[Optional[str]] = mapped_column(String(128))
    transcriptregnumber: Mapped[Optional[str]] = mapped_column(String(128))
    transcriptgivendate: Mapped[Optional[datetime.date]] = mapped_column(Date)
    access: Mapped[Optional[int]] = mapped_column(Integer)
    creditsSum: Mapped[Optional[int]] = mapped_column(Integer)
    ismarried: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    birthplace: Mapped[Optional[str]] = mapped_column(String(512))
    icnumber: Mapped[Optional[str]] = mapped_column(String(256))
    icdate: Mapped[Optional[datetime.date]] = mapped_column(Date)
    icdepartment: Mapped[Optional[str]] = mapped_column(String(256))
    education: Mapped[Optional[str]] = mapped_column(Text)
    hasExcellent: Mapped[Optional[int]] = mapped_column(TINYINT(1))
    startorder: Mapped[Optional[str]] = mapped_column(String(256))
    isStudent: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'2'"))
    certificate: Mapped[Optional[str]] = mapped_column(String(128))
    grantnumber: Mapped[Optional[str]] = mapped_column(String(256))
    rating: Mapped[Optional[int]] = mapped_column(Integer)
    GPA: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    currentCreditsSum: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True), server_default=text("'0'"))
    summerqueriesnumber: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    invalid: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    residence: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    sitizenshipID: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    diploma_number: Mapped[Optional[str]] = mapped_column(String(64))
    sport_clubs: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    national_sports: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    artist_clubs: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    diff_clubs: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    int_winner: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    rep_winner: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    reg_winner: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    city_winner: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    dorm_state: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'1'"))
    has_job: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'1'"))
    doctor_defended: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    isinretire: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    has_debts: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    fromid: Mapped[Optional[int]] = mapped_column(Integer)
    local: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    enteredinru: Mapped[Optional[str]] = mapped_column(String(256))
    enteredinkz: Mapped[Optional[str]] = mapped_column(String(256))
    enteredinen: Mapped[Optional[str]] = mapped_column(String(256))
    city: Mapped[Optional[str]] = mapped_column(String(256))
    contractid: Mapped[Optional[int]] = mapped_column(Integer)
    specializationID: Mapped[Optional[int]] = mapped_column(Integer)
    groupID: Mapped[Optional[int]] = mapped_column(Integer)
    ip_address: Mapped[Optional[str]] = mapped_column(Text)
    add_info: Mapped[Optional[str]] = mapped_column(Text)
    living_adress: Mapped[Optional[str]] = mapped_column(String(512))
    pasteduinfo: Mapped[Optional[str]] = mapped_column(Text)
    registration_place: Mapped[Optional[str]] = mapped_column(String(512))
    living_place: Mapped[Optional[str]] = mapped_column(String(512))
    seriyaAttestata: Mapped[Optional[str]] = mapped_column(String(128), server_default=text("''"))
    nomerAttestata: Mapped[Optional[str]] = mapped_column(String(128), server_default=text("''"))
    dataVydachiAttestata: Mapped[Optional[datetime.date]] = mapped_column(Date)
    naselennyiPunktAttestata: Mapped[Optional[str]] = mapped_column(String(512), server_default=text("''"))
    shcoolName: Mapped[Optional[str]] = mapped_column(Text)
    seriyaDiploma: Mapped[Optional[str]] = mapped_column(String(128), server_default=text("''"))
    dataVydachiDiploma: Mapped[Optional[datetime.date]] = mapped_column(Date)
    diplomSotlichiem: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    altynBelgi: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    auylKvota: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    firstname_en: Mapped[Optional[str]] = mapped_column(String(128))
    lastname_en: Mapped[Optional[str]] = mapped_column(String(128))
    patronymic_en: Mapped[Optional[str]] = mapped_column(String(128))
    other_birth_place: Mapped[Optional[str]] = mapped_column(String(512))
    ictype: Mapped[Optional[int]] = mapped_column(Integer)
    icseries: Mapped[Optional[str]] = mapped_column(String(255))
    end_school: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    end_college: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    end_high_school: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    end_other: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    series_number_doc_education: Mapped[Optional[str]] = mapped_column(String(255))
    date_doc_education: Mapped[Optional[datetime.date]] = mapped_column(Date)
    ball_math: Mapped[Optional[int]] = mapped_column(Integer)
    ball_history: Mapped[Optional[int]] = mapped_column(Integer)
    ball_profile: Mapped[Optional[int]] = mapped_column(Integer)
    ball_kaz_lang: Mapped[Optional[int]] = mapped_column(Integer)
    ball_rus_lang: Mapped[Optional[int]] = mapped_column(Integer)
    ball_foreign_lang: Mapped[Optional[int]] = mapped_column(Integer)
    nostrification_number_series_date: Mapped[Optional[str]] = mapped_column(String(255))
    job_place: Mapped[Optional[str]] = mapped_column(String(256))
    ball_after_uni: Mapped[Optional[int]] = mapped_column(Integer)
    ball_creative_exam: Mapped[Optional[int]] = mapped_column(Integer)
    dppage: Mapped[Optional[int]] = mapped_column(Integer)
    lastnamePrevious: Mapped[Optional[str]] = mapped_column(String(128))
    blocked: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    organization_type: Mapped[Optional[int]] = mapped_column(Integer)
    grant_type: Mapped[Optional[int]] = mapped_column(Integer)
    sirota: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"), comment='0-нет,1-сирота| ОИТ2016')
    oralman: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"), comment='0-нет,1-да| ОИТ2016')
    certificateDate: Mapped[Optional[datetime.date]] = mapped_column(Date, comment='даты выдачи сертификата | ОИТ2016')
    grantdogovorDate: Mapped[Optional[datetime.date]] = mapped_column(Date, comment='дата пр.гранта/договора | ОИТ2016')
    kta: Mapped[Optional[int]] = mapped_column(Integer, comment='0-нет, 1- будет сдавать | ОИТ2016')
    user_id: Mapped[Optional[int]] = mapped_column(Integer, comment='ID тех.секретаря таблица ayan.user')
    passwordLdap: Mapped[Optional[str]] = mapped_column(String(128))
    nostudent: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"), comment='Условное зачисление = 1')
    mobilePhone: Mapped[Optional[str]] = mapped_column(String(256))
    sum_points: Mapped[Optional[int]] = mapped_column(Integer)
    sum_points_creative: Mapped[Optional[int]] = mapped_column(Integer)
    add_infoKz: Mapped[Optional[str]] = mapped_column(Text)
    add_infoEn: Mapped[Optional[str]] = mapped_column(Text)
    academic_mobility: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    enroll_order_date: Mapped[Optional[datetime.date]] = mapped_column(Date)
    serpin2050: Mapped[Optional[int]] = mapped_column(SmallInteger, server_default=text("'0'"), comment='грант серпн')
    incorrectIin: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    assignedIinIssuedByPublicBody: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    createdDateTime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    reasonEmploymentID: Mapped[Optional[int]] = mapped_column(Integer)
    auth_key: Mapped[Optional[str]] = mapped_column(String(32), comment='ayan2018')
    password_hash: Mapped[Optional[str]] = mapped_column(String(255), comment='ayan2018')
    password_reset_token: Mapped[Optional[str]] = mapped_column(String(255), comment='ayan2018')
    emailConfirm: Mapped[Optional[int]] = mapped_column(SmallInteger, server_default=text("'20'"), comment='ayan2018')
    email_confirm_token: Mapped[Optional[str]] = mapped_column(String(255), comment='ayan2018')
    created_at: Mapped[Optional[int]] = mapped_column(Integer, comment='ayan2018')
    updated_at: Mapped[Optional[int]] = mapped_column(Integer)
    passwordLdapSSHA: Mapped[Optional[str]] = mapped_column(String(256))
    isTemporaryPassword: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"))
    firstnamePrevious: Mapped[Optional[str]] = mapped_column(String(128), server_default=text("''"))
    patronymicPrevious: Mapped[Optional[str]] = mapped_column(String(128), server_default=text("''"))
    endEducation: Mapped[Optional[int]] = mapped_column(SmallInteger)
    fromAreaID: Mapped[Optional[int]] = mapped_column(Integer)
    fromRegion: Mapped[Optional[str]] = mapped_column(String(255))
    bornInAnotherCountry: Mapped[Optional[str]] = mapped_column(String(255))
    birthAreaID: Mapped[Optional[str]] = mapped_column(String(255))
    registrationAreaID: Mapped[Optional[int]] = mapped_column(Integer)
    registrationRegion: Mapped[Optional[str]] = mapped_column(String(255))
    livingAreaID: Mapped[Optional[int]] = mapped_column(Integer)
    livingRegion: Mapped[Optional[str]] = mapped_column(String(255))
    graduatedAreaID: Mapped[Optional[int]] = mapped_column(Integer)
    graduatedRegion: Mapped[Optional[str]] = mapped_column(String(11))
    benefitsList: Mapped[Optional[str]] = mapped_column(String(255))
    sendedNbd: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    sendDateNbd: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    nbdMessage: Mapped[Optional[str]] = mapped_column(String(255))
    passwordLdapAd: Mapped[Optional[str]] = mapped_column(String(256))
    percoid: Mapped[Optional[int]] = mapped_column(Integer)
    percoidentifier: Mapped[Optional[str]] = mapped_column(String(15))
    birth_place_cato_id: Mapped[Optional[int]] = mapped_column(Integer, comment='Населенный пункт рождения (като)')
    registration_place_cato_id: Mapped[Optional[int]] = mapped_column(Integer, comment='Населенный пункт прописки (като)')
    living_place_cato_id: Mapped[Optional[int]] = mapped_column(Integer, comment='Населенный пункт проживания (като)')
    remoteAccessToTesting: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'0'"))
    naselennyi_punkt_attestata_cato_id: Mapped[Optional[int]] = mapped_column(Integer, comment='Населенный пункт учебного заведения')
    fundingID: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'-1'"), comment='Программа финансирования')
    participantID: Mapped[Optional[int]] = mapped_column(Integer, comment='Участник программы')
    is_defense_of_dissertation_in_other_hpeo: Mapped[Optional[int]] = mapped_column(TINYINT(1), comment='Защита диссертации в другом ОВПО')
    defense_of_dissertation_other_hpeo_id: Mapped[Optional[int]] = mapped_column(Integer, comment='Наименование ОВПО, в котором проходит защита диссертации')
    socialGPA: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    scientificGPA: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    integralGPA: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    serial_number: Mapped[Optional[int]] = mapped_column(Integer, comment='Порядковый номер для генерации логина/пароля')
    step: Mapped[Optional[int]] = mapped_column(SmallInteger, server_default=text("'1'"))
    enter_exam_type: Mapped[Optional[int]] = mapped_column(Integer, server_default=text("'1'"), comment='Тип поступления')
    emp_another_country: Mapped[Optional[int]] = mapped_column(TINYINT(1), server_default=text("'0'"), comment='Трудоустроен в другой стране')
