"""add chat attachments

Revision ID: 36e9fe2cb23b
Revises: b4a2d770c8e1
Create Date: 2026-04-16 10:54:17.716448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e9fe2cb23b'
down_revision: Union[str, Sequence[str], None] = 'b4a2d770c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_message_attachments_chat_id', 'chat_message_attachments', ['chat_id'], unique=False)
    op.create_index('ix_chat_message_attachments_message_id', 'chat_message_attachments', ['message_id'], unique=False)
    op.create_index('ix_chat_message_attachments_uploader_id', 'chat_message_attachments', ['uploader_id'], unique=False)
    op.alter_column('chat_messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_chat_message_attachments_uploader_id', table_name='chat_message_attachments')
    op.drop_index('ix_chat_message_attachments_message_id', table_name='chat_message_attachments')
    op.drop_index('ix_chat_message_attachments_chat_id', table_name='chat_message_attachments')
    op.drop_table('chat_message_attachments')
    # ### end Alembic commands ###
