"""add_group_chats_models

Revision ID: 77bdda3c3a10
Revises: e9b1b6a4c2d1
Create Date: 2026-06-16 11:23:43.507100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '77bdda3c3a10'
down_revision: Union[str, Sequence[str], None] = 'e9b1b6a4c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE t.typname = 'chat_participant_role'
                  AND n.nspname = 'public'
            ) THEN
                CREATE TYPE chat_participant_role AS ENUM ('admin', 'member');
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE t.typname = 'chat_type'
                  AND n.nspname = 'public'
            ) THEN
                CREATE TYPE chat_type AS ENUM ('direct', 'group');
            END IF;
        END
        $$;
        """
    )

    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column(
        'role',
        postgresql.ENUM('admin', 'member', name='chat_participant_role', create_type=False),
        server_default='member',
        nullable=False,
    ),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_participants_chat_user')
    )
    op.create_index('ix_chat_participants_chat_id', 'chat_participants', ['chat_id'], unique=False)
    op.create_index('ix_chat_participants_is_active', 'chat_participants', ['is_active'], unique=False)
    op.create_index('ix_chat_participants_role', 'chat_participants', ['role'], unique=False)
    op.create_index('ix_chat_participants_user_id', 'chat_participants', ['user_id'], unique=False)
    op.add_column(
        'chats',
        sa.Column(
            'type',
            postgresql.ENUM('direct', 'group', name='chat_type', create_type=False),
            server_default='direct',
            nullable=False,
        ),
    )
    op.add_column('chats', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('chats', sa.Column('creator_user_id', sa.Integer(), nullable=True))
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_chats_type', 'chats', ['type'], unique=False)
    op.create_foreign_key(
        'fk_chats_creator_user_id',
        'chats',
        'users',
        ['creator_user_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chats_creator_user_id', 'chats', type_='foreignkey')
    op.drop_index('ix_chats_type', table_name='chats')
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chats', 'creator_user_id')
    op.drop_column('chats', 'avatar_url')
    op.drop_column('chats', 'title')
    op.drop_column('chats', 'type')
    op.drop_index('ix_chat_participants_user_id', table_name='chat_participants')
    op.drop_index('ix_chat_participants_role', table_name='chat_participants')
    op.drop_index('ix_chat_participants_is_active', table_name='chat_participants')
    op.drop_index('ix_chat_participants_chat_id', table_name='chat_participants')
    op.drop_table('chat_participants')
    postgresql.ENUM(name='chat_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='chat_participant_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
