"""empty message

Revision ID: 79e9af55d57f
Revises: 5bf2ca5e984b
Create Date: 2026-03-19 15:16:43.191414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e9af55d57f'
down_revision: Union[str, Sequence[str], None] = '5bf2ca5e984b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_kz', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_kz'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('calendar_event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_kz', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_kz'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('calendar_event_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('structural_subdivision_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_kz', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_kz', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('needs_media_capture', sa.Boolean(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('contacts', sa.String(length=255), nullable=True),
    sa.Column('needs_tech_support', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_type_id'], ['calendar_event_type.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['calendar_event_place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_event_manager_creator_user_id', 'calendar_event_manager', ['creator_user_id'], unique=False)
    op.create_index('ix_calendar_event_manager_event_type_id', 'calendar_event_manager', ['event_type_id'], unique=False)
    op.create_index('ix_calendar_event_manager_place_id', 'calendar_event_manager', ['place_id'], unique=False)
    op.create_index('ix_calendar_event_manager_structural_subdivision_id', 'calendar_event_manager', ['structural_subdivision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_event_manager_structural_subdivision_id', table_name='calendar_event_manager')
    op.drop_index('ix_calendar_event_manager_place_id', table_name='calendar_event_manager')
    op.drop_index('ix_calendar_event_manager_event_type_id', table_name='calendar_event_manager')
    op.drop_index('ix_calendar_event_manager_creator_user_id', table_name='calendar_event_manager')
    op.drop_table('calendar_event_manager')
    op.drop_table('calendar_event_type')
    op.drop_table('calendar_event_place')
    # ### end Alembic commands ###
